### ISSUE TITLE
Hacerle borde a la nave

### ISSUE THREAD

**Issue by SoyJasson** [Lautron/lab-ODC#19]
- [ ] Probar si es fácil de hacerlo (solo debes alargar la linea y pintarla de otro color)
- [ ] Probar si queda bien

**Comment by Lautron** [comment]
Se puede hacer que el primer y ultimo pixel al dibujar una linea horizontal sean de distinto color

**Comment by SoyJasson** [comment]
Es buena idea, usar una variación de la función de pintar lineas horizontales (porque capaz no siempre queremos pintar de otro color las puntas)

**Comment by facuayala00** [comment]
Implementado
