### ISSUE TITLE
Implementar procedimiento que pueda dibujar formas complejas en base a un array

### ISSUE THREAD

**Issue by Lautron** [Lautron/lab-ODC#31]
## Posible "estructura de datos"
Podria implementarse en un array unidimensional con el siguiente formato:

![image](https://user-images.githubusercontent.com/66799530/174199513-8808e18b-dea2-4e61-9763-562d9778f75a.png)

## Pseudocodigo
```
// p -> puntero del array
// q -> puntero de inicio del subarray que se esté usando

// p = p+8 -> saltear 0
/// mientras no se haya llegado al final de p:
//    q = p+8 -> mover puntero a inicio del subarray
//    hacer un downto hasta *p
//         linea_from_array q
//         fb = pos_nueva_linea
//    mientras que *p != 0
//       p = p+8
//    p = p+8 -> mueve p a la posicion que contiene la cantidad de lineas

//linea_from_array q2
// pintar = false
// mientras que *q2 != 0
//    if pintar then
//    	pintar (*q2) pixels
//	pintar=false
//    else 
//      fb = fb + (4 * (*q2)) // mover direccion de fb (*q2) pixels hacia adelante
//      pintar=true
//    q2 = q2 + 8
```
### Comentarios
Problemente necesite un par de modificaciones, pero sirve para tener una idea general sobre que hay que hacer.
Hay que ver las siguientes cosas:
- Como saber si se llegó al final de p
- Probablemente convenga usar -1 como delimitador en vez de 0, de esa manera se evitan posibles confusiones con los elementos del subarray

**Comment by facuayala00** [comment]
Implementado
