### ISSUE TITLE
Hacer sprite del marcianito

### ISSUE THREAD

**Issue by Lautron** [Lautron/lab-ODC#8]

**Comment by Lautron** [comment]
![image](https://user-images.githubusercontent.com/66799530/174185743-e855df99-77e0-498a-9060-8d9ee73993de.png)

Hacemos el marcianito así?
@SoyJasson @facuayala00

**Comment by SoyJasson** [comment]
Por mi si

**Comment by SoyJasson** [comment]
Una vez ya tenemos el dibujo del marcianito, podemos hacer que se mueva dentro de la nave (utilizando los mismos "tiempos" que hacen que se muevan las estrellas)
Tampoco hace falta que sea un movimiento muy elaborado
O si no, hacer que desaparezca y aparezca nuevamente con una animación de este estilo:
![image](https://user-images.githubusercontent.com/45408700/174189288-bdb8be7f-1333-4be3-8c0c-0024000fac12.png)
